{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdkmain",
    "module": "games",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.2.aar",
          "url": "games-1.0.2.aar",
          "size": 318048,
          "sha512": "5bd4bf8f2cd35d28ae9c32eddf196a09018abb72ad3110b714b3dcbdb5e574ccc066f33753d2a11cdb480307dd5db0826ad7941e2eab48f81f81197389da8604",
          "sha256": "f44cc16ed70e09e16e49d8111e556c4b50e4efaf8b6329adaeb08c3044e7e507",
          "sha1": "020ee327d9de564a53c2f9048f14ffce53c6e10b",
          "md5": "e914534e6e28f23a89ba107f66cb0ee9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.airbridge",
          "module": "sdk-android",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.2.aar",
          "url": "games-1.0.2.aar",
          "size": 318048,
          "sha512": "5bd4bf8f2cd35d28ae9c32eddf196a09018abb72ad3110b714b3dcbdb5e574ccc066f33753d2a11cdb480307dd5db0826ad7941e2eab48f81f81197389da8604",
          "sha256": "f44cc16ed70e09e16e49d8111e556c4b50e4efaf8b6329adaeb08c3044e7e507",
          "sha1": "020ee327d9de564a53c2f9048f14ffce53c6e10b",
          "md5": "e914534e6e28f23a89ba107f66cb0ee9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-1.0.2-sources.jar",
          "url": "games-1.0.2-sources.jar",
          "size": 35601,
          "sha512": "1e8bb9ca5e055778af84d24c208b73606cfd223bf91da9d6881f92fdeb2664a79472f02e185f1fb3fa7d9b632b47ef7a1f6005de877a2e84086c6a84fb4db82d",
          "sha256": "f42d157f805b1b67d5407847dc0a6be60dcc4c8a74c11b007cea5e7296d6910a",
          "sha1": "e7c62e8f70f4c7462041051e2364710916696ad5",
          "md5": "1fb09bf7237aa4d6953f69b89551219f"
        }
      ]
    }
  ]
}
