{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdk",
    "module": "games",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.8.aar",
          "url": "games-1.0.8.aar",
          "size": 305978,
          "sha512": "8a0eeee1487b963e35a0cec2254aa35aa8a8b43af5b763bdd70367fd68feff349d49928987916fc929d507f420dd8536e4e6885ec03920fb081a5bd1cc429b8e",
          "sha256": "31f68a24daf74494cf48c5ba81b33049f0af3de331e36ad6f8b41a949c161448",
          "sha1": "2a2d36a19cd02a9047810a9ee0b5b84b6156fbb8",
          "md5": "4bbc0a9e695ff648e42d4efb7c86fbde"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.airbridge",
          "module": "sdk-android",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.8.aar",
          "url": "games-1.0.8.aar",
          "size": 305978,
          "sha512": "8a0eeee1487b963e35a0cec2254aa35aa8a8b43af5b763bdd70367fd68feff349d49928987916fc929d507f420dd8536e4e6885ec03920fb081a5bd1cc429b8e",
          "sha256": "31f68a24daf74494cf48c5ba81b33049f0af3de331e36ad6f8b41a949c161448",
          "sha1": "2a2d36a19cd02a9047810a9ee0b5b84b6156fbb8",
          "md5": "4bbc0a9e695ff648e42d4efb7c86fbde"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-1.0.8-sources.jar",
          "url": "games-1.0.8-sources.jar",
          "size": 33025,
          "sha512": "3a7193c412e6e49db2236232434d8b139dac29a54cfe3a84cdb8ad4e369957ce820bb6554b4d9330a678866a6217c9e456f445f609eb07d167e2bc8077ba9dc3",
          "sha256": "1a33ebdde33b2fb35e825589e59530c894af59ecd13d654af4034eb8904cd0a3",
          "sha1": "1463dcea58af2dfbbc5703c84499fdc0cfe094df",
          "md5": "a0af4fb199a4d7cea0e0aee8fa59e556"
        }
      ]
    }
  ]
}
