{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdk",
    "module": "games",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.8.aar",
          "url": "games-1.0.8.aar",
          "size": 305943,
          "sha512": "0e6c185af4b68a9de6c340b1e41dfaa7aea2644218e361883ebbb06431f766c702d1977de241eb52d50a7807ba2d315299c8adb3531d645000b4b11240fb539e",
          "sha256": "9bdb3307ee73c96651b36a866fc3a683b6fbe774f4fb99867a1c01cc00a6234b",
          "sha1": "8d43ad7d330cf276f4ad3d85b7252850629475e8",
          "md5": "adc36ccb9eb9f7075007f107d7aee1f1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.airbridge",
          "module": "sdk-android",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.8.aar",
          "url": "games-1.0.8.aar",
          "size": 305943,
          "sha512": "0e6c185af4b68a9de6c340b1e41dfaa7aea2644218e361883ebbb06431f766c702d1977de241eb52d50a7807ba2d315299c8adb3531d645000b4b11240fb539e",
          "sha256": "9bdb3307ee73c96651b36a866fc3a683b6fbe774f4fb99867a1c01cc00a6234b",
          "sha1": "8d43ad7d330cf276f4ad3d85b7252850629475e8",
          "md5": "adc36ccb9eb9f7075007f107d7aee1f1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-1.0.8-sources.jar",
          "url": "games-1.0.8-sources.jar",
          "size": 33017,
          "sha512": "962662aecba569cf44ddb705002082b9c4236fb31dbcb77c114bd36cfa0089a2bb8a89645e036d36f03d92491f4bee8a8477860f80b903346027dc48da6156e6",
          "sha256": "5a027bb6de6c2c9cf84c861b6bce0e913137aef4c6e4f29e60e611ef8a90161b",
          "sha1": "07a94694e35834505ae4384003d4ab182030b090",
          "md5": "af7f4097b24fc4fdfffc237cd7efb93b"
        }
      ]
    }
  ]
}
