{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdk",
    "module": "games",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "games-0.1.0.aar",
          "url": "games-0.1.0.aar",
          "size": 57145,
          "sha512": "90207caf4e3d80bb3114b5d4aaa02e63732e4114e78cf24a170e5eca41e03c68f6870a5328632bcd827aa7f1acd2e869df24d6c877177e02734b78fcd631af65",
          "vn.gplay.sdk.jsbridge.sha256": "6d5737ed5c08b43ce7c5ea360f8e5fc78d4b94cd83dea95b4ab0e7a52a5aaba4",
          "sha1": "24e82add7e9edbd717328acef8a76f7b4e0c8785",
          "md5": "7a955bb62edd92a2eabd988cb642d25e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "4.33.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "games-0.1.0.aar",
          "url": "games-0.1.0.aar",
          "size": 57145,
          "sha512": "90207caf4e3d80bb3114b5d4aaa02e63732e4114e78cf24a170e5eca41e03c68f6870a5328632bcd827aa7f1acd2e869df24d6c877177e02734b78fcd631af65",
          "vn.gplay.sdk.jsbridge.sha256": "6d5737ed5c08b43ce7c5ea360f8e5fc78d4b94cd83dea95b4ab0e7a52a5aaba4",
          "sha1": "24e82add7e9edbd717328acef8a76f7b4e0c8785",
          "md5": "7a955bb62edd92a2eabd988cb642d25e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-0.1.0-sources.jar",
          "url": "games-0.1.0-sources.jar",
          "size": 13599,
          "sha512": "3b1eefaf5521b5b4af8203b954719c2b97024f1cba57cce0fbf713ba00df0b72078d9b38e3b8105d483cd27d5c0fd11a2c12d385a67fd299ecbe03dbedaf5f79",
          "vn.gplay.sdk.jsbridge.sha256": "d0e052375682ed4f62a71aa373965e8f57d71c5b6f0af99b0035e423b70b8d3b",
          "sha1": "44ec53f2d804e986ed8634b2c4473fd3c6e831a5",
          "md5": "7b46983f71fd9f8623489f71aec273ee"
        }
      ]
    }
  ]
}
