{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdkmain",
    "module": "games",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.1.aar",
          "url": "games-1.0.1.aar",
          "size": 295065,
          "sha512": "9df9a03c6a83b3d73cf6d94563235213ace16784677e9a0a5e9c9cf1abebc54ab267386511a528f67c92a73b0bcd4952f738fe9363a9ee64d3c56bf8f466ce5e",
          "sha256": "43ba5f3c8d0074d6796517c09880d4449c97d0c25c20c7b7f7f2bc9529e64d7c",
          "sha1": "588e0c709930b5560968d6212244534dadf7deb8",
          "md5": "88b79d2203b12fc93195a467d861dc1e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.airbridge",
          "module": "sdk-android",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.1.aar",
          "url": "games-1.0.1.aar",
          "size": 295065,
          "sha512": "9df9a03c6a83b3d73cf6d94563235213ace16784677e9a0a5e9c9cf1abebc54ab267386511a528f67c92a73b0bcd4952f738fe9363a9ee64d3c56bf8f466ce5e",
          "sha256": "43ba5f3c8d0074d6796517c09880d4449c97d0c25c20c7b7f7f2bc9529e64d7c",
          "sha1": "588e0c709930b5560968d6212244534dadf7deb8",
          "md5": "88b79d2203b12fc93195a467d861dc1e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-1.0.1-sources.jar",
          "url": "games-1.0.1-sources.jar",
          "size": 31971,
          "sha512": "7bdbc81a3f3ff18bc8e85eb75c06c1b4363e026e3f8aed46d865c050338c2bb43f68420b81a45f5e0866ec540324eacc008d3e171454e94789a5f8d947672c8c",
          "sha256": "d71676f17cd5918b0240a5bc4959687f320ea77206c568b91a9be2dc1a624e00",
          "sha1": "07fbff12bad69fc432cf995f349edf0cce424e58",
          "md5": "f8ab50286b8398c08f6ff8494d8d3b14"
        }
      ]
    }
  ]
}
