{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdk",
    "module": "games",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.3.aar",
          "url": "games-1.0.3.aar",
          "size": 133993,
          "sha512": "9dcaab5c2c9a861a912b379bd2397b3a4d4b8128444a1f0353883954362fa526a71ef348043b669ee643dcd16dc599df865d797449af480118a296869872eb2a",
          "vn.gplay.sdk.jsbridge.sha256": "0efe9e11633f2fc8b06c257970e78e1ec6d95fb4f80cc7ff23eaf6c0f6cbdb9a",
          "sha1": "7cfed02c87b9b1890180005e5582eb93a9126691",
          "md5": "d6a7247da6342ca5a9596136ebf8a291"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "4.33.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.3.aar",
          "url": "games-1.0.3.aar",
          "size": 133993,
          "sha512": "9dcaab5c2c9a861a912b379bd2397b3a4d4b8128444a1f0353883954362fa526a71ef348043b669ee643dcd16dc599df865d797449af480118a296869872eb2a",
          "vn.gplay.sdk.jsbridge.sha256": "0efe9e11633f2fc8b06c257970e78e1ec6d95fb4f80cc7ff23eaf6c0f6cbdb9a",
          "sha1": "7cfed02c87b9b1890180005e5582eb93a9126691",
          "md5": "d6a7247da6342ca5a9596136ebf8a291"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-1.0.3-sources.jar",
          "url": "games-1.0.3-sources.jar",
          "size": 17191,
          "sha512": "2ab675ea413a2d014f21c64df2af91be81c6a1c12e73107a247df3735bca9d1361cb1b93719bddf6acf692cd9dd20c032b69f6b352e04fa773116bcfa3cf751d",
          "vn.gplay.sdk.jsbridge.sha256": "62836adb453e29024c89cca41fcefe4c5ee3826e945b9cb0479d542b5f24ee33",
          "sha1": "378c3cb95c36c13cfb06eedaea4e6a14decc45cc",
          "md5": "6067b243b30d23af04f722121e7d841c"
        }
      ]
    }
  ]
}
