{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.gplay.sdk",
    "module": "games",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.1.aar",
          "url": "games-1.0.1.aar",
          "size": 129288,
          "sha512": "5462932475638e0b6661738245584af9df87da2be899454a07d2df1dea125dd79fab8cb5f4a2c48dd7bd26490e32c243532722d4482220788ca01ffaf28fdcff",
          "vn.gplay.sdk.jsbridge.sha256": "066f94f6038675e701db8a26f1f723157f77473306a236692e135d13067de9bd",
          "sha1": "fb0c8dcd852a8f6dc226888808d78ba045ec1ff4",
          "md5": "357e0c60935b4e498df65008fd14a3c2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.adjust.sdk",
          "module": "adjust-android",
          "version": {
            "requires": "4.33.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime"
        },
        {
          "group": "androidx.core",
          "module": "core-splashscreen",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-script-runtime",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "games-1.0.1.aar",
          "url": "games-1.0.1.aar",
          "size": 129288,
          "sha512": "5462932475638e0b6661738245584af9df87da2be899454a07d2df1dea125dd79fab8cb5f4a2c48dd7bd26490e32c243532722d4482220788ca01ffaf28fdcff",
          "vn.gplay.sdk.jsbridge.sha256": "066f94f6038675e701db8a26f1f723157f77473306a236692e135d13067de9bd",
          "sha1": "fb0c8dcd852a8f6dc226888808d78ba045ec1ff4",
          "md5": "357e0c60935b4e498df65008fd14a3c2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "games-1.0.1-sources.jar",
          "url": "games-1.0.1-sources.jar",
          "size": 15793,
          "sha512": "492d72bae7c52713cc5f28622fdf59660a4eb07834fb1376c9b8e6d4cc5316846de22329022e22924acddd5a89affb759cca03e7770aa45675918fc8cbf79667",
          "vn.gplay.sdk.jsbridge.sha256": "efa9f4610c92421a1664a75c7f1cef4067d1951ac92d2590a6a28c7e8f588b0d",
          "sha1": "a4541e0ae40627702f3614b9d6da2cfbc98e1df4",
          "md5": "c0822605cc92ddb5fbb348b43052fbc2"
        }
      ]
    }
  ]
}
